language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  include:
    - php: 5.6
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
  allow_failures:
    -  php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - if [ -z "$dependencies" ]; then travis_retry composer install --no-interaction; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest --no-interaction; fi;
  - if [ "$dependencies" = "highest" ]; then travis_retry composer update --no-interaction; fi;
  - composer show

script:
  - ./vendor/bin/phpunit -v --coverage-text --coverage-clover=./build/logs/clover.xml

after_success:
  - if [ -f ./build/logs/clover.xml ]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar; fi
  - if [ -f ./build/logs/clover.xml ]; then php ./php-coveralls.phar -v; fi
