language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 5.6
          env: deps=low
        - php: 5.6
          env: deps=high
        - php: 7.0
        - php: hhvm
    fast_finish: true

env:
    global:
        - deps=no

before_install:
  - composer self-update

install:
  - if [ "$deps" = "no" ]; then composer install --prefer-source; fi;
  - composer require satooshi/php-coveralls:dev-master

script:
  - if [ "$deps" = "high" ]; then composer update --prefer-source; fi;
  - if [ "$deps" = "low" ]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi;
  - phpunit -v --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
